# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a90e557598264929bc90a156693b81cc6c4c643fc683356f4d9109cec42ea80ee72e566ba3ef237fd5ba8f1e841d5d1e1aa547b31b1d49b398a9ea626e64761

test:
  secret_key_base: fcabd09d1f7b300f1f6bd956df2e3cb2784c8eb48f640125044ad451d31648551d7d329b392debd957c07ef875bcd2f810ef15725c03cc2c8a29c5f83157841b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
